server:
  port: 8092

spring:
  application:
    name: knowledge-service
  config:
    import: optional:file:./config.yaml
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1GB

logging:
  config: classpath:log4j2-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info
