business-intelligence:
  cors-origin: "*"
  runtime:
    base-dir: "./data"
    cache-enabled: true
  logging:
    access-log-enabled: true

logging:
  level:
    root: INFO
    com.huawei.opsfactory.businessintelligence: INFO
    org.springframework: WARN
