server:
  port: 8093

spring:
  application:
    name: business-intelligence
  config:
    import: optional:file:./config.yaml

logging:
  config: classpath:log4j2-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info
